### ISSUE TITLE
Which companies are using SkyWalking RocketBot

### ISSUE THREAD

**Issue by TinyAllen** [TinyAllen/rocketbot#15]
Daocloud+www.daocloud.io

**Comment by wu-sheng** [comment]
Ref https://github.com/apache/incubator-skywalking/issues/443  Share the users to SkyWalking main repo. Also welcome and encourage everyone to send a pull request to add you into the official list

https://github.com/apache/incubator-skywalking/blob/master/docs/powered-by.md

**Comment by xuxinping** [comment]
Nacosaas

**Comment by TinyAllen** [comment]
@xuxinping Thanks😁, could you tell me your company website or logo?

**Comment by wu-sheng** [comment]
Could we close and unpin this? Also remove https://github.com/TinyAllen/rocketbot#who-uses-skywalking-rocketbot .

As we are moving in Apache as primary UI, all SkyWalking users will be using this UI :)
