### ISSUE TITLE
通过nginx加载dist里面的文件加载不到数据

### ISSUE THREAD

**Issue by R1hug0** [TinyAllen/rocketbot#18]
用项目里面的nginx配置还是加载不了数据,一直是提示404,有啥办法排除吗,打包是用npm install
npm run build 生成的dist静态文件,

**Comment by R1hug0** [comment]
The nginx configuration as follows:
user  appuser;
worker_processes  1;

error_log  /opt/logs/nginx/error.log warn;
pid        /opt/nginx/nginx.pid;

events {
    worker_connections  10240;
}

http {

    upstream skywalkingLB {
      server 127.0.0.1:8080; 
    }

    include       mime.types;
    default_type  application/octet-stream;

    rewrite_log on;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /opt/logs/nginx/access.log  main;

    gzip on;
    gzip_min_length 1k;
    gzip_buffers 4 16k;
    gzip_http_version 1.0;
    gzip_comp_level 6;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
    gzip_vary off;

    sendfile        on;

    keepalive_timeout  65;

    server {
        listen       80;
        server_name  _;

        location /api {
            rewrite ^/(.*) /graphql break;
            proxy_pass http://skywalkingLB;
        }

        location / {
            root   /opt/app/static;
            try_files $uri $uri/ /index.html =404;
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }
}
nginx error messages  as follows :
192.168.1.200 - - [05/Nov/2018:15:57:29 +0800] "POST /api/applications HTTP/1.1" 404 122 "http://192.168.1.3/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0" "-"

**Comment by R1hug0** [comment]
I put static files in /opt/app/static

**Comment by JaredTan95** [comment]
@R1hug0 I checked out that no errors in your configuration. You can request the interface from the HTTP simulation tool, like`postman`. Btw,see if the Skywalkng UI has data in response.

**Comment by R1hug0** [comment]
I tested the log display 404 ,  is rewrite configuration error or npm build problem?

**Comment by JaredTan95** [comment]
If Skywalking UI display 404, that means your Skywalking Collector works bad or it's 12800 port not expose for UI. You can join the WeChat-Group for discussing through Scan QR code.

**Comment by R1hug0** [comment]
Skywalking UI use normal,  so maybe   /api  rewrite configuration  does not  work.

**Comment by JaredTan95** [comment]
SkyWalking UI 's authentication defines in UI in hard code way. And RocketBot latest code has Login page through another API.

**Comment by R1hug0** [comment]
nice, It seems normal.

**Comment by JaredTan95** [comment]
@R1hug0 You can find more info about auth in https://github.com/TinyAllen/rocketbot/blob/develop/nginx.conf.

**Comment by R1hug0** [comment]
ok,tks!
