### ISSUE TITLE
Which license does this project use? who owns the copyright?

### ISSUE THREAD

**Issue by wu-sheng** [TinyAllen/rocketbot#2]
1. What kind of license? Apache 2.0, MIT or something else?
1. Who owns this project? This is a personal project supported by daocloud.io or copyright daocloud.io?

**Comment by wu-sheng** [comment]
I have seen you commit LICENSE as MIT, owned by the author. Could you tell me more about how to define **power by daocloud lab**? Can I think it is `sponsor by`?

**Comment by TinyAllen** [comment]
Daocloud Lab is one of the Daocloud's departments，it's fullname is Nat Appliaction Transformation. It is also the department witch I am in.

**Comment by wu-sheng** [comment]
Powered by meaning daocloud is using this project. Is that what you try to say? I am just asking. 

Copyright and license are good enough for me.
