### ISSUE TITLE
Incompatible issue with SkyWalking on Istio

### ISSUE THREAD

**Issue by wu-sheng** [TinyAllen/rocketbot#21]
One of SkyWalking 6 new feature is that,  support Istio telemetry data. @hanahmily just try to set the UI in our test env today, but find out, it doesn't work well. I think he has reported the bugs to the project. Still, I create this issue to track.

**Comment by TinyAllen** [comment]
@wu-sheng Many thanks ! l have already received the reply from hanahmily. l will keep track of it.

**Comment by wu-sheng** [comment]
Fixed in new release.
