### ISSUE TITLE
请问这个SKYWALKING_URL如何 配置

### ISSUE THREAD

**Issue by fanzhi1977** [TinyAllen/rocketbot#26]
`docker run -p 8080:80 -d -e SKYWALKING_URL=127.0.0.1:1234,127.0.0.1:1235 SKYWALKING_COMMON=127.0.0.1:8080,127.0.0.1:80801 rocketbot`
按照skywalking的安装文档https://github.com/apache/incubator-skywalking/blob/v5.0.0-GA/docs/cn/Deploy-backend-in-cluster-mode-CN.md，有以下端口：
10800，11800和12800这几个，都试过不能用。
无法进行登录。

**Comment by fanzhi1977** [comment]
> rocketbot-skywalking_1      | 2018/11/15 16:53:30 [error] 12#12: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 10.9.144.76, server: localhost, request: "POST /api/check HTTP/1.1", upstream: "http://10.1.8.16:12800/graphql", host: "10.33.123.16:8888", referrer: "http://10.33.123.16:8888/login"
> rocketbot-skywalking_1      | 10.9.144.76 - - [15/Nov/2018:16:53:30 +0800] "POST /api/check HTTP/1.1" 502 537 "http://10.33.123.16:8888/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36" "-"
> 
使用docker跑rocketbot，这是错误信息。

**Comment by JaredTan95** [comment]
@fanzhi1977 `SKYWALKING_URL`

**Comment by JaredTan95** [comment]
@fanzhi1977 Can `http://10.1.8.16:12800/graphql` be sent in the browser directly .`SKYWALKING_URL` is the env of skywalking graphql API. If you are using release branch source code , 'SKYWALKING_COMMON' is the port of  skwalking-appweb. BTW, `SKYWALKING_COMMON` config has abounded in the latest version(master or develop branch).

**Comment by gamefundas** [comment]
I am thinking your host collector IP 10.1.8.16 is not accessible for docker container. What do you get when you hit http://10.1.8.16:12800/graphql directly? It should throw an error saying only POST is supported something which should indicate the web api is working.

Then you can narrow down to see why docker is unable to access it.
