### ISSUE TITLE
页面空间布局问题

### ISSUE THREAD

**Issue by YoungHu** [TinyAllen/rocketbot#29]
问题如截图显示。

<img width="546" alt="wx20181123-141242 2x" src="https://user-images.githubusercontent.com/7418602/48930293-7aa37e00-ef2a-11e8-91e1-8541d56a4f32.png">
<img width="1648" alt="wx20181123-141540 2x" src="https://user-images.githubusercontent.com/7418602/48930294-7aa37e00-ef2a-11e8-8d43-5ce928c5e496.png">

**Comment by TinyAllen** [comment]
l will fix this in the next version.

**Comment by YoungHu** [comment]
BTW, there are something wrong with the alarm page. it just show the start time but title, type, content is missing, skywalking UI show it normal. sorry for no screenshot.

**Comment by TinyAllen** [comment]
@YoungHu l will check it, Could you please tell me this missing appearing is in which version ? Skywalking 5.x or 6.x version.

**Comment by YoungHu** [comment]
> @YoungHu l will check it, Could you please tell me this missing appearing is in which version ? Skywalking 5.x or 6.x version.

6.x
