### ISSUE TITLE
提个建议-ui display logs tags

### ISSUE THREAD

**Issue by landonzeng** [TinyAllen/rocketbot#3]
首先感谢作者提供的ui，很漂亮也很喜欢，今天部署在公司的服务器上与skywalking ui进行了比较，发现缺少了一个功能，skywalking ui中有个Service模块，里面可以查看每个接口的sql语句，这个很详细，是否能在rocketbot中也加入这个功能，这样很方便后期在ui中排查每个接口的问题
![qq 20181018101045](https://user-images.githubusercontent.com/7336781/47127107-536be800-d2be-11e8-9f74-80b86729ac7b.png)

**Comment by TinyAllen** [comment]
谢谢你的支持，此功能将会在明天的新版本更新中添加进去。

**Comment by TinyAllen** [comment]
新版本中已经添加好了此项功能。
