### ISSUE TITLE
建议能否提供namespace支持

### ISSUE THREAD

**Issue by astrisk** [TinyAllen/rocketbot#30]
类似在kubernetes上，会用namesapce来隔离环境，不同的namespace中，会有同名的service。而且界面展示，没有namespace过滤可以个比较麻烦的事情。

**Comment by TinyAllen** [comment]
@astrisk 这个不是前端的问题，我只与官方保持一致，namespace需要skywalking本身支持才行，如果需要查询多个namespace的话目前只有部署多套skywalking了。

**Comment by astrisk** [comment]
@TinyAllen 今天刚看了官方的文档，5.0的里面的是有namespace的支持的，https://github.com/apache/incubator-skywalking/blob/v5.0.0-GA/docs/cn/Namespace-CN.md，如果前端需要支持这个，方便增加吗？
