### ISSUE TITLE
刷新trace页面，筛选条件里面的日期不是之前选择的

### ISSUE THREAD

**Issue by jjlu521016** [TinyAllen/rocketbot#32]
在trace页面选择时间之后，再次刷新trace页面，筛选条件里面的日期不是之前选择的。
跟踪代码看了下在 `src/views/components/trace/search-box.vue`的 `mounted`方法里面，重新替换了之前选择的时间。

**Comment by TinyAllen** [comment]
@jjlu521016 I will check it
