### ISSUE TITLE
请问SkyeWalking server地址如何配置

### ISSUE THREAD

**Issue by yanmingbi** [TinyAllen/rocketbot#34]
你好 我依照https://github.com/TinyAllen/rocketbot/blob/master/README.md教程 在windows操作系统
clone了rocketbot工程, 修改了nginx.conf (在upstream skywalkingLB中增加了ip:12800这个server), 之后
在本地依次执行了npm install  npm start, 此时, 可以在浏览器访问rocketbot的界面, 但是没有任何监控信
息展示.
     PS: 我使用curl http://ip:12800/graphql 返回 {"errors":[{"message":null}]} (在Skywalking的webapp.yml中配置了username和password).

-----------------------------
请问, 
     1.我的整个部署 启动流程正确吗 ? 
     2.rocketbot没有任何监控信息展示是因为curl http://ip:12800/graphql返回{"errors":[{"message":null}]} 吗?

**Comment by JaredTan95** [comment]
ip:12800/graphql 貌似是没有GET请求的，都是需要通过POST传入graphql查询语句。

**Comment by JaredTan95** [comment]
另外，npm start貌似并不是走的nginx，你本地开发可以改这里的配置。https://github.com/TinyAllen/rocketbot/blob/master/config/index.js

**Comment by yanmingbi** [comment]
@JaredTan95 感谢 我去试一下.
