### ISSUE TITLE
请问rocketbot登录界面的username password在哪里设置 ? 

### ISSUE THREAD

**Issue by yanmingbi** [TinyAllen/rocketbot#35]
我依照https://github.com/TinyAllen/rocketbot/blob/master/README.md 在本地搭建rocketbot, 修改了conf/index.js, 可以连接到demo rocketbot. 当我修改conf/index.js的target连接我搭建的skywalking(在webapp/webapp.yml中配置了username和password admin/123456)时, 输入admin/123456无法登陆, 无法进入rocketbot展示界面. 

请问rocketbot登录界面的username和password应该在哪儿配置? 谢谢.

**Comment by TinyAllen** [comment]
The username and password of the frontend page are written in the code. The username and password of the skywalking backend are for port 8080. You can add the api into the login.vue source code and i have witten something notice about this api in  login.vue.

**Comment by yanmingbi** [comment]
@TinyAllen  thank you.
