### ISSUE TITLE
trace中时间与全局时间不对应

### ISSUE THREAD

**Issue by zouyx** [TinyAllen/rocketbot#40]
![image](https://user-images.githubusercontent.com/3828072/54018570-ff599580-41c3-11e9-974f-5e82662d6eda.png)
全局时间是0时区，trace中时间依然是本地时区

**Comment by TinyAllen** [comment]
trace的时间和全局的时间是不绑定的，搜索条件以上面的timerang为准

**Comment by zouyx** [comment]
明白，但是我想问的是，很容易以为改了全局时间，在进去这个页面的时候误以为时间是带进去，而不知道是需要修改该时间。很难才发现的了需要去改这个时间。

**Comment by TinyAllen** [comment]
全局时间是第一次进去trace时上面时间自动选择的依据，我可以写个notice

**Comment by zouyx** [comment]
🙏

**Comment by JaredTan95** [comment]
Considering global user and apache features. English, please.
