### ISSUE TITLE
[Donation] Remove all old copyrights announcement

### ISSUE THREAD

**Issue by wu-sheng** [TinyAllen/rocketbot#46]
After SGA/ICLAs submit, also before the transfer happens, please remove all announcements about
`supported By DaoCloud Labs`, including words, badges, and links.

**Comment by TinyAllen** [comment]
Fixed: https://github.com/TinyAllen/rocketbot/commit/d49282aa0379d20910e824f4daee3656a44145cb

**Comment by wu-sheng** [comment]
We just need to fix this because repository transfer happens:) Thanks for changing so quickly.
