### ISSUE TITLE
[Binding 6.1.0 release] Restore heatmap dashboard widget

### ISSUE THREAD

**Issue by wu-sheng** [TinyAllen/rocketbot#51]
Heatmap needs to be supported. I know we have `scatter diagram`, of course we could have, but `heat map` is introduced in many places of Google SRE talks. So it will make sense more to global user. Don't need to remove `scatter diagram`.

**Comment by TinyAllen** [comment]
fixed 294c97edbe1051a2155ffa16d4859872f4f4a545
