### ISSUE TITLE
[Binding 6.1.0 release] Auto refresh supported

### ISSUE THREAD

**Issue by wu-sheng** [TinyAllen/rocketbot#55]
Metric, topology should support auto-refresh. Another feature is provided in current skywalking UI.

**Comment by TinyAllen** [comment]
Update: f16128c726ae3d3ae30c103320072d79b8823a11 

auto refresh in 6s

![屏幕快照 2019-03-26 下午9 41 28](https://user-images.githubusercontent.com/19775780/55001680-1b589600-5010-11e9-8e19-9017d4c252a9.png)

**Comment by wu-sheng** [comment]
Thanks. We need wait you to fix the seaech condition refresh unexpected issue fixed. Then auto refresh should be useful

**Comment by nielinjie** [comment]
Can I enable this auto refreshing by default? i mean that when I open the web page by input address.
