### ISSUE TITLE
Heatmap is not clear to read

### ISSUE THREAD

**Issue by wu-sheng** [TinyAllen/rocketbot#58]
![image](https://user-images.githubusercontent.com/5441976/54476539-a16b2480-4839-11e9-8b6b-77d57192504e.png)

**Comment by wu-sheng** [comment]
All these nodes have different values, but look like same.

**Comment by TinyAllen** [comment]
Update: f16128c726ae3d3ae30c103320072d79b8823a11

![屏幕快照 2019-03-26 下午9 39 42](https://user-images.githubusercontent.com/19775780/55001512-b4d37800-500f-11e9-9639-2e3ab5ec4d31.png)
