### ISSUE TITLE
发现个样式问题-css style

### ISSUE THREAD

**Issue by landonzeng** [TinyAllen/rocketbot#6]
是否能将前景色和字体颜色设置成别的颜色，目前的颜色字体和前景色是一样的，不选中没办法看到是什么内容。如图：
![qq 20181019110802](https://user-images.githubusercontent.com/7336781/47195730-b24d6200-d38f-11e8-8c26-588e01da5aa7.png)

**Comment by TinyAllen** [comment]
新版本中已经修复了
