### ISSUE TITLE
Endpoint backend search is not available

### ISSUE THREAD

**Issue by wu-sheng** [TinyAllen/rocketbot#67]
Endpoint search is supported at the backend, but UI hasn't supported that. We need to fix this, this has high priority for the demo.

**Comment by wu-sheng** [comment]
Also, TopN widget in each level(global, service, maybe DB slow statement and slow traces) is not supporting the copy/paste, which let me very hard to find the endpoint.

**Comment by TinyAllen** [comment]
fixed: f16128c726ae3d3ae30c103320072d79b8823a11

#### What I do
I fix this bug without using the backend search query. l use a large $limit number to get all the endpoint, this way can make frontend select easier and require no extra requests and waiting times.

**Comment by wu-sheng** [comment]
Endpoint could the tens of thousands. So, I think we still need the search at backend.

**Comment by TinyAllen** [comment]
fixed 294c97edbe1051a2155ffa16d4859872f4f4a545
