### ISSUE TITLE
Miss endpoint dependency graph

### ISSUE THREAD

**Issue by wu-sheng** [TinyAllen/rocketbot#73]
Dependency graph, show the relationship between endpoint.

**Comment by JaredTan95** [comment]
![image](https://user-images.githubusercontent.com/12468337/55770772-1ab40b00-5ab8-11e9-8e5a-37d0b4a019d7.png)

**Comment by TinyAllen** [comment]
fixed 294c97edbe1051a2155ffa16d4859872f4f4a545
