### ISSUE TITLE
docker 启动报错

### ISSUE THREAD

**Issue by cpp288** [TinyAllen/rocketbot#78]
镜像从hub上拿的，还是git上编译的，都出现下面的错误信息
/usr/share/run.sh: line 43: syntax error: bad substitution

**Comment by JaredTan95** [comment]
fixed.

**Comment by jxttian** [comment]
> fixed.

how to fix it

**Comment by jxttian** [comment]
+ set -e
+ absolute_path=/etc/nginx/nginx.conf
+ ngx_upstream_file=/etc/nginx/nginx.conf
+ pool_name=skywalkingLB
+ skywalking_collector=127.0.0.1:1234,127.0.0.1:1235
+ awk 'BEGIN{list="127.0.0.1:1234,127.0.0.1:1235";split(list,ip_list,",");for(ip in ip_list){print ip_list[ip];}}'
+ pool_ip='127.0.0.1:1234
127.0.0.1:1235'
/usr/share/run.sh: line 42: syntax error: bad substitution
