### ISSUE TITLE
Trace优化建议

### ISSUE THREAD

**Issue by landonzeng** [TinyAllen/rocketbot#9]
提个意见，在Trace这个地方能不能提供一个过滤health的筛选，这样就可以筛选出每一个真实接口的数据出来，因为心跳检查会每5秒一次，所以基本上进入Trace会有大量的health的记录，会影响跟踪查看正式环境的接口信息的问题定位效率，所以是否能提供一个过滤，筛选出所有非健康检查的数据，建议再添加一个筛选条件栏，这样可以和其他筛选条件配合着用
![_20181024112448](https://user-images.githubusercontent.com/7336781/47404325-72b3bb00-d77f-11e8-85fc-58a097e6acbc.png)

**Comment by landonzeng** [comment]
还有就是界面上是否可以添加定时刷新的功能，比如可以选择5秒刷新一次

**Comment by feelwing1314** [comment]
这个不应该UI做的事情，可以通过skywalking的ignore插件实现，直接在agent收集的时候过滤掉/health，以及任何你自定义的接口。
